# -*- coding: utf-8 -*-
"""Meu primeiro algoritimo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ttrVKZCuWhsi6NFQNhoBvk7_apEZpOD
"""

nome = input("Digite o nome do usuário ") #Aguarde o usuário digitar algo
print(nome)

valor = input('Digite a nota ')

print (nome, 'sua nota foi:', valor)

valor = input('Digite o valor do produto: ')
print(valor)

desconto = int(valor) - 5

valor_convert = int(valor)
desconto = valor_convert - 5
print(desconto)

desconto = int(valor) - 5
print(desconto)